apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources
  #- elasticsearch
  - metrics-server
  #- kubectl-pod
  #- redis
  - ClusterRole
  - storageClass
  #- mariadb
  #- minio
  #- redmine
